# Thank you for using WaterHomes!
# Documentation: https://github.com/WatermanMC/WaterHomes/wiki
# Discord: https://discord.gg/Scgqfm5EU4
# GitHub: https://github.com/WatermanMC/WaterHomes

# Teleport Delay
# Bypass permission: waterhomes.tpdelay.bypass
tp-delay:
  enabled: true
  cancel-on-move: true
  duration: 2 # In seconds


# Teleport Cooldown
# Bypass permission: waterhomes.cooldown.bypass
tp-cooldown:
  enabled: true
  duration: 60 # In seconds


# Banned words for sethome
# Regex pattern is allowed
# Bypass permission: waterhomes.bannedwords.bypass
banned-words:
  - banned words is listed here
  - th(i|1)s is (a|4) reg(3|3)x pattern


# Here you can customize for home limits
# Permission: waterhomes.sethome.<group>
# For example, you set 'default' to create only 1 home. You need to give a group/user the permission: waterhomes.sethome.default
home-group-limits:
  default: 1
  god: 10

# List unsafe blocks here so players cannot set home at this blocks
# Use Minecraft block identifier here, not numerical! You may try googling if you dont know :D
# Bypass permission: waterhomes.unsafeblocks.bypass
# This detects within 2 block radius of player
# Case insensitive
unsafe-blocks:
  - water
  - lava
  - cactus
  - magma_block
  - bedrock
